version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    security-updates-only: true
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 3
    security-updates-only: true
    labels:
      - ci
    commit-message:
      prefix: "ci(deps)"
