services:
  postgres:
    image: postgres:latest
    container_name: turbo-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"