export const SPLIT_FRIEND_NAME_MAX = 120;
export const SPLIT_FRIEND_ALIAS_MAX = 80;
export const GATHERING_NAME_MAX = 120;
export const GATHERING_EXPENSE_DESCRIPTION_MAX = 200;
export const SUGGEST_FRIENDS_DEFAULT_LIMIT = 10;
export const SUGGEST_FRIENDS_MAX_LIMIT = 20;
